configurations:
# first configuration
# |
# V
- plane:
    xDim    : 3840  # pixels
    yDim    : 2160  # pixels
    distance: 0.25  # meters
    fov     : 43.5  # degrees
  lightSource:
    ringLights:
    - led:
        model            : D2 - Stanley Electric JGN1105H-TR
        intensity        : 0.05 # W/sr
        # must contain 19 values, ranging from 0° to 90° (5° step), inbetween angle is calculated using linear approximation
        radiationProfile :  # relative, in range 0 -> 1
        - 1
        - 0.9
        - 0.73
        - 0.5
        - 0.4
        - 0.25
        - 0.15
        - 0.1
        - 0.09
        - 0.08
        - 0.08
        - 0.07
        - 0.07
        - 0.06
        - 0.06
        - 0.05
        - 0.05
        - 0
        - 0
      radius      : 0.08  # meters
      tilt        : 5     # degrees
      numberOfLeds: 15

      # second ringlight
      # |
      # V
   #- led: ... 

# second configuration
# |
# V
#- plane: ... (begin at the begining of the row, do not indent)